### ISSUE TITLE
pod 설치및 firebase 연동

### ISSUE THREAD

**Issue by babbayo** [aboutNext/About#1]
https://firebase.google.com/docs/ios/setup?hl=ko

**Comment by babbayo** [comment]
질문사항!
1. println 으로 로그 찍어보고 싶은데 에러남!
Use of unresolved identifier 'println'
![image](https://user-images.githubusercontent.com/45893424/67619162-3227cb00-f833-11e9-908b-2f9c84728c21.png)

2. 버튼을 GIDSignInButton 클래스로 바꾸고 싶음
엔터를 치면 사라지고 희미하게 UIButton 으로 됨
![image](https://user-images.githubusercontent.com/45893424/67619187-597e9800-f833-11e9-89d0-3f2ab4abbed6.png)

3. 문서대로 했는데, 에러가남 
handle 함수 에 파라미터가 어떻게 되는지 확인하고 싶은데 어떻게 알수 있을지 모르겠음
https://firebase.google.com/docs/auth/ios/google-signin
![image](https://user-images.githubusercontent.com/45893424/67619261-5cc65380-f834-11e9-8818-12688140a5a3.png)

@jasmine-shin 윤서언니~ 도와줘요~

**Comment by babbayo** [comment]
일단 주석처리해둠!

**Comment by jasmine-shin** [comment]
@babbayo  일단 프린트는 print(변수명), print("스트링") 으로 써보시옹

**Comment by jasmine-shin** [comment]
@babbayo 해결완료.
